# Generated by Django 6.1 on 2026-08-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField()),
                ('source', models.CharField(default='Jobicy', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
